config/routes.rb
FakeTower::Application.routes.draw do

  resources :teams, only: :show

  resources :projects do

  	resources :messages, only: [:index, :show, :new, :create] do
  		member do
  			post 'create_comment'
  		end
  	end

  	resources :task_lists, except: [:edit, :update]

  	resources :todos # The RESTful interface still in progress

  end

  root :to => 'home#index'
  
  devise_for :members
end

app/models/comment.rb
class Comment
  include Mongoid::Document

  field :content, type: String
  field :author_id, type: String
  field :author_name, type: String

  validates :content, presence: true

  ## Associations
  # To alternative choices,
  # embed might be a better approach than belongs_to

  embedded_in :todo
  embedded_in :message
end

app/models/member.rb
class Member
  include Mongoid::Document

  after_create :if_root

  def self.ranks
    [
      [1, 'Super user'],
      [2, 'Admin'],
      [3, 'User'],
      [4, 'Guest']
    ]
  end

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""
  field :username, :type => String, :default => ""
  field :rank, :type => Integer, :default => 1

  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Validations
  validates_inclusion_of :rank, :in => (1..4).to_a

  ## Associations
  has_and_belongs_to_many :projects, inverse_of: :members
  has_and_belongs_to_many :teams, inverse_of: :members

  has_many :todos

  # What the member currently at
  belongs_to :current_team, class_name: "Team", inverse_of: :current_members

  private
  def if_root
    if self.rank == 1
      team = Team.create! name: "#{self.username}'s team"
      self.teams.push team
      self.current_team = team
      self.save
    end
  end

end

app/models/message.rb
class Message
  include Mongoid::Document
  field :title, type: String
  field :content, type: String

  embeds_many :comments
  belongs_to :project
end

app/models/project.rb
class Project
  include Mongoid::Document
  field :name, type: String

  ## Associations
  has_and_belongs_to_many :members, inverse_of: :projects
  has_many :messages, dependent: :destroy
  has_many :task_lists, dependent: :destroy

end

app/models/task_list.rb
class TaskList
  include Mongoid::Document
  field :name, type: String

  belongs_to :project
  has_many :todos, dependent: :destroy
end

app/models/team.rb
class Team
  include Mongoid::Document

  ## Associations

  has_and_belongs_to_many :members, inverse_of: :teams
  # The team members that currently work for the team
  has_many :current_members, class_name: "Member", inverse_of: :current_team

  # The projects that own by the member in the current team
  def projects(member)
  	if members.include? member
  		member.projects
  	else
  		[]
  	end
  end
end

app/models/todo.rb
class Todo
  include Mongoid::Document
  field :content, type: String

  belongs_to :task_list
  belongs_to :owner, :class_name => 'Member'
  embeds_many :comments
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  	if member_signed_in?
  		redirect_to team_path(current_member.current_team)
  	end
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

	respond_to :json, :html
	# respond_to :json, :html, only: :show

	before_filter :current_project

	def index
		@messages = @project.messages
		respond_with @project, @messages
	end

	def show
		@message = @project.messages.find(params[:id])
		respond_with @message
	end

	def new
		@message = @project.messages.build
		respond_with @project, @message
	end

	def create
		@message =  @project.messages.create(params[:message])
		respond_with @project, @message
	end

	def create_comment
		@message = @project.messages.find(params[:id])
		comment = @message.comments.create! params[:comment]

		data = "{ \"message_id\": \"#{@message._id}\", \"comment\": #{comment.to_json} }"
		$redis.publish 'message-comment', data

		send_data 'OK'
	end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	before_filter :current_projects
	respond_to :json, :html

	def index
		respond_with @projects
	end

	def show
		@project = @projects.find(params[:id])
		respond_with @project
	end

	def new
		@project = @projects.build
		respond_with @project
	end

	def create
		respond_with @projects.create(params[:project])
	end

	def edit
		respond_with @projects.find(params[:id])
	end

	def update
		respond_with @projects.update(params[:id], params[:project])
	end

	def destroy
		respond_with @projects.destroy(params[:id], params[:project])
	end

	private
	def current_projects
		authenticate_member!

		# authentication for the project
		# must be in the name of the current_member
		@projects = current_member.current_team.projects(current_member)
	end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
	respond_to :json, :html

	before_filter :authenticate_member!

	def show
	end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
	respond_to :json
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/task_lists_helper.rb
module TaskListsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/_login_bar.html.erb
<ul class="nav pull-right">
  <% if member_signed_in? %>
  <li><%= link_to current_member.username, edit_member_registration_path %></li>
  <li><%= link_to 'Logout', destroy_member_session_path, method: :delete %>
  </li>
  <% else %>
  <li><%= link_to 'Sign up', new_member_registration_path %></li>
  <li><%= link_to 'Sign in', new_member_session_path %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "FakeTower" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">FakeTower</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
            <%= render 'layouts/login_bar' %>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>